from __future__ import annotations

from typing import Protocol


class BaseStorage(Protocol):
    async def get(self, key: str) -> dict | None: ...
    async def set(self, key: str, data: dict) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def touch(self, *keys: str) -> None: ...
